name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches: [main] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 

      - name: 安装依赖
        run: npm install 

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write 
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js 并配置 npm registry
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/ 
          cache: 'npm' 

      - name: 安装依赖（确保环境一致）
        run: npm ci 

      - name: 生成 OTP 验证码
        id: otp
        run: |
          npm install -g otpauth
          OTP=$(npx otpauth --secret ${{ secrets.NPM_2FA_SECRET }})
          echo "otp=$OTP" >> $GITHUB_ENV
        env:
          NPM_2FA_SECRET: ${{ secrets.NPM_2FA_SECRET }} 

      - name: 发布到 npm
        run: npm publish --access public --otp ${{ env.otp }} 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }} 