name: Node.js Package

on:
  push:
    branches: [main] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 

      - name: 安装依赖
        run: npm install 

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write 
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js 并配置 npm registry
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/ 
          cache: 'npm' 

      - name: 安装依赖（确保环境一致）
        run: npm ci 

      - name: 发布到 npm
        run: npm publish --access public 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }} 